### ISSUE TITLE
训练时报错RuntimeError

### ISSUE THREAD

**Issue by lilith9999** [DCSong/CRNN-DenseNet#4]
训练时报错：
`RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xx/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xx/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "main.py", line 89, in collate_fn
    image_data = torch.stack(img_data, dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [1, 18, 27] at entry 0 and [1, 18, 25] at entry 1`
是因为数据集的图片宽高不一致吗？请问如何解决此问题呢？

**Comment by dechaosong** [comment]
由于我使用的训练集图片是同样长度的，所以注释掉了此逻辑。简单的思路是将每张图片都填充到统一尺寸，或者填充到该batch内的最大尺寸
例如，img_data[i] = cv2.copyMakeBorder(img_data[i], 0, 0, 0, width - 280, borderType=cv2.BORDER_CONSTANT, value=255)

**Comment by dechaosong** [comment]
相关思路被注释在main_v2.py的collec_fn函数中，如果高度也不一致，则需要先做resize再填充
