### ISSUE TITLE
cv2.error

### ISSUE THREAD

**Issue by lilith9999** [DCSong/CRNN-DenseNet#5]
同样的数据集，运行main.py时无报错，但是运行main_v2.py时报错：
Train Epoch: 1  Batch_Loss: 4.3797  Epoch_Loss: 11.4039  CER: 1.0000  SER: 1.0000:  77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                  | 54/70 [00:24<00:07,  2.24it/s]Traceback (most recent call last):
  File "main_v2.py", line 316, in <module>
    train(model, optimizer, epoch, train_loader)
  File "main_v2.py", line 198, in train
    for batch_index, (img_data, target, target_lengths) in enumerate(pbar):
  File "/home/xx/anaconda3/envs/ocr/lib/python3.8/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/xx/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/xx/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/xx/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/xx/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/home/xx/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xx/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xx/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "main_v2.py", line 62, in __getitem__
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
图片路径检查了，没问题的，想请教一下为什么会有这个报错。
另：是否方便提供您训练中文数据集时的参数如何调整？

**Comment by dechaosong** [comment]
这应该是图片的文件名有错误，导致没有读取到图片。建议检查一下文件名是否为中文，或绝对/相对路径是否正确，定位到这张图片debug排查一下
目前提供的是训练中英文数据集时使用的参数，如果想要更好的效果，建议在数据集、网络结构和超参调节方面尝试
